# Generated by Django 4.2.3 on 2024-09-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_keywords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='video',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
